---
# tasks file for wordpress
- name: install (wp-cli)
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: "{{ wordpress_wp_cli_install_dir }}/wp-cli"
    force: true
    owner: root
    group: root
    mode: 0755
  tags: [configuration, wordpress, wordpress-wp-cli-install]

- name: check download
  shell: "ls {{ wordpress_path }} | grep -q 'wp-'"
  register: check_download
  failed_when: False
  changed_when: False
  tags: [configuration, wordpress, wordpress-is-downloaded]

- name: download
  shell: "wp-cli --allow-root --no-color --path='{{ wordpress_path }}' core download"
  when: check_download.rc != 0
  tags: [configuration, wordpress, wordpress-downloaded]

- name: configure
  shell: "wp-cli --allow-root --no-color --quiet --path='{{ wordpress_path }}' core config --dbname='{{ wordpress_dbname }}' --dbuser='{{ wordpress_dbuser }}' --dbpass='{{ wordpress_dbpass }}' --dbhost='{{ wordpress_dbhost }}'"
  args:
    creates: "{{ wordpress_path }}/wp-config.php"
  tags: [configuration, wordpress, wordpress-configure]

- name: check installation
  shell: "wp-cli --allow-root --no-color --path='{{ wordpress_path }}' core is-installed"
  register: check_installation
  failed_when: False
  changed_when: False
  tags: [configuration, wordpress, wordpress-is-installed]

- name: install
  shell: "wp-cli --allow-root --no-color --path='{{ wordpress_path }}' core install --url='{{ wordpress_url }}' --title='{{ wordpress_title }}' --admin_name='{{ wordpress_admin_name }}' --admin_email='{{ wordpress_admin_email }}' --admin_password='{{ wordpress_password }}'"
  when: check_installation.rc != 0
  tags: [configuration, wordpress, wordpress-install]

- name: check installation (theme)
  shell: "wp-cli --allow-root --no-color --path='{{ wordpress_path }}' theme is-installed {{ item }}"
  register: check_installation_themes
  failed_when: False
  changed_when: False
  with_items: wordpress_install_themes
  when: wordpress_install_themes
  tags: [configuration, wordpress, wordpress-is-installed-theme]

- name: install (theme)
  shell: "wp-cli --allow-root --no-color --path='{{ wordpress_path }}' theme install {{ item.item }} --activate"
  with_items: check_installation_themes.results
  when: wordpress_install_themes and item.rc != 0
  tags: [configuration, wordpress, wordpress-install-theme]

- name: check installation (plugin)
  shell: "wp-cli --allow-root --no-color --path='{{ wordpress_path }}' plugin is-installed {{ item }}"
  register: check_installation_plugins
  failed_when: False
  changed_when: False
  with_items: wordpress_install_plugins
  when: wordpress_install_plugins
  tags: [configuration, wordpress, wordpress-is-installed-plugin]

- name: install (plugin)
  shell: "wp-cli --allow-root --no-color --path='{{ wordpress_path }}' plugin install {{ item.item }} --activate"
  with_items: check_installation_plugins.results
  when: wordpress_install_plugins and item.rc != 0
  tags: [configuration, wordpress, wordpress-install-plugin]
